services:
  backend:
    build:
      context: ./backend
    container_name: orpheus-backend
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - websocket_network

  celery:
    build:
      context: ./backend
    container_name: orpheus-celery
    command: celery -A backend worker --loglevel=info --concurrency=4
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    networks:
      - websocket_network

  assets:
    build:
      context: ./backend/assets
    container_name: orpheus-assets
    volumes:
      - ./backend/assets:/assets
    ports:
      - "5000:5000"  # Expose on host
    networks:
      - websocket_network

  redis:
    image: redis:7
    container_name: orpheus-redis
    ports:
      - "6379:6379"
    networks:
      - websocket_network

  frontend:
    build:
      context: ./frontend
    container_name: orpheus-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  websocket_network:
